name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Task
      uses: arduino/setup-task@v1
    - name: Install Soroban
      run: cargo install --locked --version 20.0.0-rc.4.1 soroban-cli
    - name: Run tests
      run: task test
